# Generated by Django 5.2.4 on 2025-07-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealership', '0003_remove_dealershipmodel_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipAdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('watches', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=120)),
                ('model_of_car', models.CharField(max_length=120)),
                ('description_of_car', models.CharField(max_length=700)),
                ('seller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='dealership.dealershipmodel')),
            ],
            options={
                'db_table': 'dealership_advertisement',
            },
        ),
        migrations.CreateModel(
            name='DealershipCarImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_of_car', models.ImageField(blank=True, upload_to='images')),
                ('advertisement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='dealership_advertisement.dealershipadvertisementmodel')),
            ],
            options={
                'db_table': 'dealership_images',
            },
        ),
    ]
