# Generated by Django 5.2.4 on 2025-07-15 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipadvertisementmodel',
            name='car_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
    ]
