# Generated by Django 5.2.4 on 2025-07-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_advertisement', '0002_dealershipadvertisementmodel_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershipcarimagemodel',
            name='advertisement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dealership_advertisement.dealershipadvertisementmodel'),
        ),
    ]
