# Generated by Django 5.2.4 on 2025-07-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('watches', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=120)),
                ('model_of_car', models.CharField(max_length=120)),
                ('description_of_car', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
        migrations.CreateModel(
            name='CarImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_of_car', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
