# Generated by Django 5.2.4 on 2025-07-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carimagemodel',
            name='advertisement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='apps.advertisementmodel'),
        ),
    ]
