# Generated by Django 5.2.4 on 2025-07-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_dealershipstaffmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealershipStaffModel',
        ),
    ]
