# Generated by Django 5.2.4 on 2025-07-15 11:55

import core.services.file_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_delete_dealershipstaffmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimagemodel',
            name='image_of_car',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_advertisement_photo),
        ),
    ]
