# Generated by Django 5.2.4 on 2025-07-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_carimagemodel_image_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimagemodel',
            name='advertisement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apps.advertisementmodel'),
        ),
    ]
