# Generated by Django 5.2.4 on 2025-07-16 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_carimagemodel_advertisement'),
        ('dealership', '0004_remove_dealershipmodel_advertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='advertisement_status',
            field=models.CharField(default='unavailable', max_length=30),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='car_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealership_ads', to='dealership.dealershipmodel'),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='failed_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_advertisements', to=settings.AUTH_USER_MODEL),
        ),
    ]
