# Generated by Django 5.2.3 on 2025-07-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealershipmodel',
            name='staff',
        ),
    ]
