# Generated by Django 5.2.4 on 2025-07-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0003_remove_dealershipmodel_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealershipmodel',
            name='advertisement',
        ),
    ]
