# Generated by Django 5.2.4 on 2025-07-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipstaffmodel',
            name='can_change_staff_rights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealershipstaffmodel',
            name='can_hire_workers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealershipstaffmodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
