# Generated by Django 5.2.4 on 2025-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(default='seller', max_length=30),
        ),
    ]
